"""add poster_file_id to movies and series

Revision ID: 261f345a9c36
Revises: 7d9557bef1bd
Create Date: 2026-07-04 17:48:28.313018

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '261f345a9c36'
down_revision: str | None = '7d9557bef1bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_file_id', sa.String(length=255), nullable=True))
    op.add_column('series', sa.Column('poster_file_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'poster_file_id')
    op.drop_column('movies', 'poster_file_id')
    # ### end Alembic commands ###
