"""add source_channel to movies and series

Revision ID: 4ab4f34687b0
Revises: 261f345a9c36
Create Date: 2026-07-08 17:00:22.657629

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '4ab4f34687b0'
down_revision: str | None = '261f345a9c36'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_MANBA_PREFIX = '📡 Manba: '


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('source_channel', sa.String(length=255), nullable=True))
    op.add_column('series', sa.Column('source_channel', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

    # Before this migration, the source-channel tag briefly lived in
    # ``description`` (formatted as "📡 Manba: <channel>") — move it into the new
    # dedicated column and clear it back out of ``description`` so that field is
    # free for an actual synopsis, matching what every row before this stopgap
    # (and every row after this migration) already looks like.
    for table in ('movies', 'series'):
        op.execute(
            f"UPDATE {table} SET source_channel = substring(description from length('{_MANBA_PREFIX}') + 1), "
            f"description = NULL WHERE description LIKE '{_MANBA_PREFIX}%'"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'source_channel')
    op.drop_column('movies', 'source_channel')
    # ### end Alembic commands ###
