"""add series and seasons

Revision ID: 7d9557bef1bd
Revises: a9b71f656617
Create Date: 2026-07-04 16:39:18.547993

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7d9557bef1bd'
down_revision: str | None = 'a9b71f656617'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_title'), 'series', ['title'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'number', name='uq_seasons_series_id_number')
    )
    op.create_index(op.f('ix_seasons_series_id'), 'seasons', ['series_id'], unique=False)
    op.add_column('movies', sa.Column('season_id', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('episode_number', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_movies_season_id'), 'movies', ['season_id'], unique=False)
    op.create_foreign_key(None, 'movies', 'seasons', ['season_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.drop_index(op.f('ix_movies_season_id'), table_name='movies')
    op.drop_column('movies', 'episode_number')
    op.drop_column('movies', 'season_id')
    op.drop_index(op.f('ix_seasons_series_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_series_title'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
